DROP TABLE IF EXISTS hit;

CREATE TABLE IF NOT EXISTS hits
(
    id        bigint generated by default as identity not null,

    app       VARCHAR(32)                             NOT NULL,
    uri       VARCHAR(128)                            NOT NULL,
    ip        VARCHAR(16)                             NOT NULL,
    timestamp timestamp WITHOUT TIME ZONE             NOT NULL
);